
import ./[typst_gen_decl]
when gen_t:
  import ./export_typst
  import std/macros
  import std/compilesettings
  import std/strformat
  from std/os import searchExtPos, `/`, relativePath
  import std/paths
  import std/strutils
  proc nimRstToTypst(s: string): string =
    ## a very very simple rst to typst converter, only for doc comments in this project, not a general solution
    ##  and it does quite a few things
    s.replace("*/", r"""#"\u{2a}\u{2f}";""")
  const posOnlyButGotKwPre = "only pos-args allowed, but got kw-arg: "
  proc posOnlyBodyImpl(argsName: string): string =
    result = argsName & ".pos()"
    result = '{' & fmt"""
let named = {argsName}.named();
assert(named.len() == 0, message: "only pos-args allowed but got kw-args: " + repr(named)); {result}""" & '}'
  const posOnlyChkName = "__nim_posOnlyChk"
  const posOnlyImpl = "#let " & posOnlyChkName & "(x) = " & posOnlyBodyImpl("x")
  template posOnly(argsName: string): string = posOnlyChkName & '(' & argsName & ')'
  proc addTypstCode(result: var string, wasm_plugin_name: string, funcName: string; params: NimNode; doc: NimNode) =
    when exportNimDocToTypst:
      if not doc.isNil:
        result.add "/*"
        result.add doc.strVal.nimRstToTypst()
        result.add "*/\n"
    result.add &"#let {funcName}("
    var sparams = newSeq[string](params.len)
    for i, p in params:
      let first = p[0]
      if p.kind == nnkPrefix:
        assert first.strVal == "*"
        let s = p[1].strVal
        sparams[i] = posOnly(s)  # args.pos() -> array of positional args
        result.add ".."
        result.add s
      else:
        let s = first.strVal
        sparams[i] = s
        result.add s
        if not p[1].isNil:
          result.add ':' & p[1].strVal
      result.add ','
    result.add ')'

    result.add &" = cbor({wasm_plugin_name}.{funcName}("
    for s in sparams:
      result.add &"cbor.encode({s}),"
    result.add ')'

    result.add ")\n"
  proc toTypstCode(): tuple[projName, code: string] =
    let wasm_plugin_name = "__nim_plugin"
    let projNameNim = querySetting projectName
    let projPath = querySetting projectPath
    let outDir = querySetting(outDir).relativePath(projPath, '/')
    let pos = projNameNim.searchExtPos()
    let projName = if pos >= 0: projNameNim[0 ..< pos] else: projNameNim
    result.projName = projPath / projName
    let wasmName = projName & ".wasm"
    result.code = &"""
// Generated by wasm_minimal_protocol for Nim
{posOnlyImpl}
#let {wasm_plugin_name} = plugin("{outDir/wasmName}")
#let {wasm_plugin_name} = plugin.transition({wasm_plugin_name}.wasm_minimal_protocol_NimMain)
"""
    for (f, spec) in collectTypstExports.pairs:
      when exportNimDocToTypst:
        let
          params = spec[0]
          doc = spec[1]
      else:
        let params = spec
        const doc: NimNode = nil
      result.code.addTypstCode(wasm_plugin_name, f, params, doc)
  template genTypstFile*() =
    bind toTypstCode, gen_typst
    static:
      let (projName, typstCode) = toTypstCode()
      writeFile(
        if gen_typst.len == 0 or gen_typst == "true": projName & ".typ" else: gen_typst,
        typstCode
      )

else:
  template genTypstFile*() = discard
