
import ./[typst_gen_decl]
when gen_t:
  import ./export_typst
  import std/macros
  import std/compilesettings
  import std/strformat
  from std/os import searchExtPos, `/`
  import std/paths
  proc addTypstCode(result: var string, wasm_plugin_name: string, funcName: string; params: NimNode) =
    result.add &"#let {funcName}("
    for p in params:
      result.add p[0].strVal
      if not p[1].isNil:
        result.add ':' & p[1].strVal
      result.add ','
    result.add ')'

    result.add &" = cbor({wasm_plugin_name}.{funcName}("
    for p in params:
      result.add &"cbor.encode({p[0].strVal}),"
    result.add ')'

    result.add ")\n"
  proc toTypstCode(): tuple[projName, code: string] =
    let wasm_plugin_name = "wasm_minimal_protocol_nim_plugin"
    let projNameNim = querySetting projectName
    let projPath = querySetting projectPath
    let pos = projNameNim.searchExtPos()
    let projName = if pos >= 0: projNameNim[0 ..< pos] else: projNameNim
    result.projName = projPath / projName
    let wasmName = projName & ".wasm"
    result.code = &"""
// Generated by wasm_minimal_protocol for Nim
#let {wasm_plugin_name} = plugin("{wasmName}")
#let _ = {wasm_plugin_name}.wasm_minimal_protocol_NimMain()
"""
    for (f, params) in collectTypstExports.pairs:
      result.code.addTypstCode(wasm_plugin_name, f, params)
  template genTypstFile*() =
    bind toTypstCode, gen_typst
    static:
      let (projName, typstCode) = toTypstCode()
      writeFile(
        if gen_typst.len == 0 or gen_typst == "true": projName & ".typ" else: gen_typst,
        typstCode
      )

else:
  template genTypstFile*() = discard
