// Generated by wasm_minimal_protocol for Nim
#let wasm_minimal_protocol_nim_plugin = plugin("../bin/t_example_lib.wasm")
#let _ = wasm_minimal_protocol_nim_plugin.wasm_minimal_protocol_NimMain()
#let frexp(x,) = cbor(wasm_minimal_protocol_nim_plugin.frexp(cbor.encode(x),))
#let hello() = cbor(wasm_minimal_protocol_nim_plugin.hello())
#let hypot(x,y,) = cbor(wasm_minimal_protocol_nim_plugin.hypot(cbor.encode(x),cbor.encode(y),))
#let runeLen(s,) = cbor(wasm_minimal_protocol_nim_plugin.runeLen(cbor.encode(s),))
#let str_count(s,sub,) = cbor(wasm_minimal_protocol_nim_plugin.str_count(cbor.encode(s),cbor.encode(sub),))
#let withDefaultArgs(a,b:42,c:"default",) = cbor(wasm_minimal_protocol_nim_plugin.withDefaultArgs(cbor.encode(a),cbor.encode(b),cbor.encode(c),))
