// Generated by wasm_minimal_protocol for Nim
#let wasm_minimal_protocol_nim_plugin = plugin("t_gen_typst.wasm")
#let _ = wasm_minimal_protocol_nim_plugin.wasm_minimal_protocol_NimMain()
#let frexp(x) = cbor(wasm_minimal_protocol_nim_plugin.frexp(cbor.encode(x)))
#let hypot(x,y) = cbor(wasm_minimal_protocol_nim_plugin.hypot(cbor.encode(x),cbor.encode(y)))
